alias ll="ls -lrth"
alias la="ls -alrth"
alias gst="git status"
alias hgrep="history | grep"
alias ca="source /bigdata/Jessin/Softwares/miniforge3/bin/activate"
alias seqp="cd /bigdata/Jessin/Sequencing_projects/"
alias soft="cd /bigdata/Jessin/Softwares"
alias scripts="cd /bigdata/Jessin/Scripts"
